[build]
  functions = "functions"
  command = "npm run build"
  publish = "build"

[template.environment]
  FAUNADB_SECRET = "Your FaunaDB Server Secret"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"