[build]
  functions = "netlify/functions"

[template.environment]
  FAUNADB_SERVER_SECRET = "Your FaunaDB Server Secret"

[[redirects]]
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/:splat"