version: "3"

services:
  server:
    image: server
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    network_mode: host
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app

  db:
    image: postgres:alpine
    network_mode: host
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=portfolio

  web:
    image: web
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/opt/app/src

volumes:
  postgres_data:
