version: "3"

services:
  server:
    image: kasiawinkler/portfolio:server
    build: .
    network_mode: host
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8000:8000"

  db:
    image: postgres:alpine
    network_mode: host
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=portfolio

  web:
    image: kasiawinkler/portfolio:web-production
    build: ../
    network_mode: host
    depends_on:
      - db
      - server
    ports:
      - "80:80"

volumes:
  postgres_data:
